name: partix
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  dart_mappable: ^4.5.0
  get_it: ^7.6.0
  flutter_bloc: ^9.1.1
  blocy: ^1.0.10
  go_router: ^10.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.2.1
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.9.1
  country_code_picker: ^3.3.0
 
  meta: ^1.16.0
  url_launcher: ^6.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - asset/image/

  fonts:
    - family: SFPro
      fonts:
        - asset: asset/fonts/SF-Pro-Display-Ultralight.otf
          weight: 200
        - asset: asset/fonts/SF-Pro-Display-Thin.otf
          weight: 300
        - asset: asset/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: asset/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: asset/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: asset/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: asset/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: asset/fonts/SF-Pro-Display-Black.otf
          weight: 900